### ISSUE TITLE
python program is stacked when trying to open a huge shelf

### ISSUE THREAD

**Issue by moshik1** [IBM/mcas#135]
When I tried to open a huge shelf, the python program is stacked.
I have /mnt/pmem0/ of 792GB  (The machine is "sg-pmem2")
>  ndctl list
[
  {
    "dev":"namespace0.0",
    "mode":"fsdax",
    "map":"dev",
    "size":792721358848,
    "uuid":"a5f23831-4f38-473b-a913-c77836a2b725",
    "sector_size":512,
    "align":2097152,
    "blockdev":"pmem0"
  }
] 

> When I tried to open 300000MB - working which is OK
>>> s = pymm.shelf('myShelf',size_mb=300000,pmem_path='/mnt/pmem0',force_new=True)
[LOG]: Backend_instance_mgr: (hstore-cc) (/mnt/pmem0) ()
[LOG]: load_backend: (hstore-cc) (/mnt/pmem0) ()
[LOG]: dax config: [{"path":"/mnt/pmem0","addr":38654705664}]
[LOG]: CCA init /home/moshikh/mcas_pymm/src/lib/libccpm/src/cca.cpp:72 0x55be11d924c0 (clear)

> When I tried to open 1000000MB - fail since it is larger then /mnt/pmem0 size - which is OK
>>> s = pymm.shelf('myShelf',size_mb=1000000,pmem_path='/mnt/pmem0',force_new=True)
[LOG]: Backend_instance_mgr: (hstore-cc) (/mnt/pmem0) ()
[LOG]: Matching backend exists!
[LOG]: arena_fs::region_create posix_fallocate: 1048576000000: No space left on device
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/moshikh/.local/lib/python3.6/site-packages/McasApiPackage-0.2-py3.6-linux-x86_64.egg/pymm/shelf.py", line 71, in __init__
    self.mr = MemoryResource(name, size_mb, pmem_path=pmem_path, backend=backend, mm_plugin=mm_plugin, force_new=force_new)
  File "/home/moshikh/.local/lib/python3.6/site-packages/McasApiPackage-0.2-py3.6-linux-x86_64.egg/pymm/memoryresource.py", line 95, in __init__
    super().__init__(pool_name=name, size_mb=size_mb, pmem_path=pmem_path, backend=backend, mm_plugin=mm_plugin, force_new=force_new)
RuntimeError: unable to create/open pool

But!!!! when trying to open 600000 MB the python program is stack 
>>> s = pymm.shelf('myShelf',size_mb=600000,pmem_path='/mnt/pmem0',force_new=True)
[LOG]: Backend_instance_mgr: (hstore-cc) (/mnt/pmem0) ()
[LOG]: Matching backend exists!
[LOG]: CCA init /home/moshikh/mcas_pymm/src/lib/libccpm/src/cca.cpp:72 0x55be11d97020 (clear)
.....

**Comment by moshik1** [comment]
I rebuild MCAS  again and it worked
