### ISSUE TITLE
re-assign tensor

### ISSUE THREAD

**Issue by moshik1** [IBM/mcas#170]
**When trying to reassign tensor after changing the size "view", the re-assignment is failed:**
**- Create tensor**
>>> s.c = pt.tensor([[1, 2, 3], [4, 5, 6], [9,10,11]])
[LOG]: get_attribute: key not found
[LOG]: get_attribute: key not found
[LOG]: get_attribute: key not found
[LOG]: get_attribute: key not found
[LOG]: HSTORE lock /home/moshikh/mcas_pymm/src/components/store/hstore/src/session.tcc:430 0x55d86144a230 allocating object 72 bytes
[LOG]: HSTORE put /home/moshikh/mcas_pymm/src/components/store/hstore/src/hstore.cpp:345 0x55d861454880 (key=c) (value=��)
[LOG]: HSTORE put /home/moshikh/mcas_pymm/src/components/store/hstore/src/hstore.cpp:345 0x55d861454880 (key=c) (value=��)
[LOG]: put: already locked
made torch_tensor instance from copy 'c' on shelf

- **re-assign - fail**
>>> **s.c = s.c.view(9,-1)**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/moshikh/.local/lib/python3.6/site-packages/MicroMcasApiPackage-0.1-py3.6-linux-x86_64.egg/pymm/shelf.py", line 200, in __setattr__
    self.erase(name)
  File "/home/moshikh/.local/lib/python3.6/site-packages/MicroMcasApiPackage-0.1-py3.6-linux-x86_64.egg/pymm/check.py", line 25, in _f
    return f(*args, **kwargs)
  File "/home/moshikh/.local/lib/python3.6/site-packages/MicroMcasApiPackage-0.1-py3.6-linux-x86_64.egg/pymm/shelf.py", line 287, in erase
    self.mr.erase_named_memory(name)
  File "/home/moshikh/.local/lib/python3.6/site-packages/MicroMcasApiPackage-0.1-py3.6-linux-x86_64.egg/pymm/check.py", line 25, in _f
    return f(*args, **kwargs)
  File "/home/moshikh/.local/lib/python3.6/site-packages/MicroMcasApiPackage-0.1-py3.6-linux-x86_64.egg/pymm/memoryresource.py", line 197, in erase_named_memory
    super()._MemoryResource_erase_named_memory(name)
RuntimeError: erase failed unexpectedly

**Assign to a new variable - succeed** 
>>> s.c1 = s.c.view(9,-1)
[LOG]: get_attribute: key not found
[LOG]: get_attribute: key not found
[LOG]: get_attribute: key not found
[LOG]: get_attribute: key not found
[LOG]: HSTORE lock /home/moshikh/mcas_pymm/src/components/store/hstore/src/session.tcc:430 0x55d86144a230 allocating object 72 bytes
[LOG]: HSTORE put /home/moshikh/mcas_pymm/src/components/store/hstore/src/hstore.cpp:345 0x55d861454880 (key=c1) (value=��)
[LOG]: HSTORE put /home/moshikh/mcas_pymm/src/components/store/hstore/src/hstore.cpp:345 0x55d861454880 (key=c1) (value=��)
[LOG]: put: already locked
made torch_tensor instance from copy 'c1' on shelf

**Comment by dwaddington** [comment]
You are using a view and thus have a self-recursion problem.  We can see if it is possible to implicitly cast the view to create a copy.

**Comment by dwaddington** [comment]
To achieve what you want, you need to clone the rhs.

        shelf.c = shelf.c.clone().view(9,-1)

**Comment by dwaddington** [comment]
I have put in the logic to raise an exception in this case.  Implicit cast is not possible because of reference count held by the view.

**Comment by moshik1** [comment]
Another re-assign issue:
I think F.nll_loss(...) create another reference that points to Y_hat that we can't clear

65         s.Y_hat: pt.Tensor = m.forward(s.X)
66         loss: pt.Tensor = F.nll_loss(s.Y_hat.cpu(), s.Y_gt.cpu())
67         s.erase('Y_hat')

Traceback (most recent call last):
  File "mnist_pymm_nopos.py", line 225, in <module>
    main()
  File "mnist_pymm_nopos.py", line 196, in main
    args.cuda)
  File "mnist_pymm_nopos.py", line 67, in train_one_epoch
    s.erase('Y_hat')
  File "/home/moshikh/.local/lib/python3.6/site-packages/MicroMcasApiPackage-0.1-py3.6-linux-x86_64.egg/pymm/check.py", line 25, in _f
    return f(*args, **kwargs)
  File "/home/moshikh/.local/lib/python3.6/site-packages/MicroMcasApiPackage-0.1-py3.6-linux-x86_64.egg/pymm/shelf.py", line 293, in erase
    self.mr.erase_named_memory(name)
  File "/home/moshikh/.local/lib/python3.6/site-packages/MicroMcasApiPackage-0.1-py3.6-linux-x86_64.egg/pymm/check.py", line 25, in _f
    return f(*args, **kwargs)
  File "/home/moshikh/.local/lib/python3.6/site-packages/MicroMcasApiPackage-0.1-py3.6-linux-x86_64.egg/pymm/memoryresource.py", line 197, in erase_named_memory
    super()._MemoryResource_erase_named_memory(name)


I upload the code to moshik2 branch:
in this path:
https://github.com/IBM/mcas/tree/moshik2/examples/paper_examples/posterior_estimation_HPEC2021/experiments
running the experiment is with: this command:
python3 mnist_pymm_nopos.py  model_4fc -p /mnt/nvme0/models/  -f /mnt/pmem0 -c -1 -s 4000 -e1 -b 100 --results_filepath pymm.txt

**Comment by dwaddington** [comment]
Did you try clone on the right hand side?  What does m.formward do?
Erase fails when it is still locked by something, usually a shelf variable.

**Comment by moshik1** [comment]
This issue of re-assign is connected to issue #171 with grad_fn
>>> **s.x = pt.tensor([[1., 2, 3], [4, 5, 6], [9,10,12]], requires_grad=True)**
releasing named memory x-value @ 0x9005ffed8
[LOG]: persisting memory @0x9005ffed8
releasing named memory x @ 0x9007ffd98
[LOG]: persisting memory @0x9007ffd98
[LOG]: get_attribute: key not found
[LOG]: get_attribute: key not found
[LOG]: get_attribute: key not found
[LOG]: get_attribute: key not found
[LOG]: HSTORE lock /home/moshikh/mcas/src/components/store/hstore/src/session.tcc:430 0x558654d2d230 allocating object 36 bytes
[LOG]: HSTORE put /home/moshikh/mcas/src/components/store/hstore/src/hstore.cpp:345 0x558654d37510 (key=x) (value=��)
[LOG]: HSTORE put /home/moshikh/mcas/src/components/store/hstore/src/hstore.cpp:345 0x558654d37510 (key=x) (value=��)
[LOG]: put: already locked
made torch_tensor instance from copy 'x' on shelf

>>> **s.x**
releasing named memory c-value @ 0x9005ffe98
[LOG]: persisting memory @0x9005ffe98
releasing named memory c @ 0x9007ffd18
[LOG]: persisting memory @0x9007ffd18
**tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 9., 10., 12.]], grad_fn=<AliasBackward>)**

**Can't re-assign to s.x** 
>>> **s.x = s.x + 1**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/moshikh/.local/lib/python3.6/site-packages/MicroMcasApiPackage-0.1-py3.6-linux-x86_64.egg/pymm/shelf.py", line 206, in __setattr__
    self.erase(name)
  File "/home/moshikh/.local/lib/python3.6/site-packages/MicroMcasApiPackage-0.1-py3.6-linux-x86_64.egg/pymm/check.py", line 25, in _f
    return f(*args, **kwargs)
  File "/home/moshikh/.local/lib/python3.6/site-packages/MicroMcasApiPackage-0.1-py3.6-linux-x86_64.egg/pymm/shelf.py", line 287, in erase
    raise RuntimeError('erase failed due to outstanding references ({})'.format(count))
**RuntimeError: erase failed due to outstanding references (3)**

**can assign to torch_tensor**
>>> x = s.x + 1
>>> x
tensor([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [10., 11., 13.]], grad_fn=<AliasBackward>)
>>>

clone does not help:
>>> **s.x = s.x.clone() + 1**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/moshikh/.local/lib/python3.6/site-packages/MicroMcasApiPackage-0.1-py3.6-linux-x86_64.egg/pymm/shelf.py", line 206, in __setattr__
    self.erase(name)
  File "/home/moshikh/.local/lib/python3.6/site-packages/MicroMcasApiPackage-0.1-py3.6-linux-x86_64.egg/pymm/check.py", line 25, in _f
    return f(*args, **kwargs)
  File "/home/moshikh/.local/lib/python3.6/site-packages/MicroMcasApiPackage-0.1-py3.6-linux-x86_64.egg/pymm/shelf.py", line 293, in erase
    self.mr.erase_named_memory(name)
  File "/home/moshikh/.local/lib/python3.6/site-packages/MicroMcasApiPackage-0.1-py3.6-linux-x86_64.egg/pymm/check.py", line 25, in _f
    return f(*args, **kwargs)
  File "/home/moshikh/.local/lib/python3.6/site-packages/MicroMcasApiPackage-0.1-py3.6-linux-x86_64.egg/pymm/memoryresource.py", line 197, in erase_named_memory
    super()._MemoryResource_erase_named_memory(name)
RuntimeError: erase failed unexpectedly
