### ISSUE TITLE
can't assign tensor with autograd

### ISSUE THREAD

**Issue by moshik1** [IBM/mcas#171]
>>> s.x = pt.tensor([2., 3.], requires_grad=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/moshikh/.local/lib/python3.6/site-packages/MicroMcasApiPackage-0.1-py3.6-linux-x86_64.egg/pymm/shelf.py", line 214, in __setattr__
    self.__dict__[name] = pymm.torch_tensor.build_from_copy(self.mr, name, value)
  File "/home/moshikh/.local/lib/python3.6/site-packages/MicroMcasApiPackage-0.1-py3.6-linux-x86_64.egg/pymm/torch_tensor.py", line 81, in build_from_copy
    shape = tensor.numpy(),
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

Work for regular variable 
>>> x = pt.tensor([2., 3.], requires_grad=True)
>>>

**Comment by moshik1** [comment]
Fixed: 
Added change from tensor.numpy() -> tensor.detach().numpy()
Commited to pymm branch
diff --git a/src/python/pymm/torch_tensor.py b/src/python/pymm/torch_tensor.py
index 308659429..97268eae8 100644
--- a/src/python/pymm/torch_tensor.py
+++ b/src/python/pymm/torch_tensor.py
@@ -78,11 +78,11 @@ class torch_tensor(Shadow):
     def build_from_copy(memory_resource: MemoryResource, name: str, tensor):
         new_tensor = shelved_torch_tensor(memory_resource,
                                           name,
-                                          shape = tensor.numpy(),
+                                          shape = tensor.detach().numpy(),
                                           dtype = tensor.dtype)

         # now copy the data
-        np.copyto(new_tensor._base_ndarray, tensor.to('cpu').numpy())
+        np.copyto(new_tensor._base_ndarray, tensor.to('cpu').detach().numpy())

 #        if tensor.dim() is 0:
 #            new_tensor.data = tensor.clone()

**Comment by moshik1** [comment]
**The fix is not enough, since it omit the argument of the shelf: for example: requires_grad=True**
>>> a = pt.tensor([2., 3.], requires_grad=True)
**>>> a
tensor([2., 3.], requires_grad=True)**

>>> s.a = pt.tensor([2., 3.], requires_grad=True)
[LOG]: get_attribute: key not found
[LOG]: get_attribute: key not found
[LOG]: get_attribute: key not found
[LOG]: get_attribute: key not found
[LOG]: HSTORE lock /home/moshikh/mcas/src/components/store/hstore/src/session.tcc:430 0x55c62b150ac0 allocating object 8 bytes
[LOG]: HSTORE put /home/moshikh/mcas/src/components/store/hstore/src/hstore.cpp:345 0x55c62b15ac20 (key=a1) (value=��)
[LOG]: HSTORE put /home/moshikh/mcas/src/components/store/hstore/src/hstore.cpp:345 0x55c62b15ac20 (key=a1) (value=��)
[LOG]: put: already locked
made torch_tensor instance from copy 'a1' on shelf
**>>> s.a
tensor([2., 3.])**

**Comment by moshik1** [comment]
Add commit to pymm that support requires_grad in shelf.torch_tensor
But....
The grad_fn is not correct:
>>> x = pt.tensor([2., 3.], Backward")
KeyboardInterrupt
>>> x = pt.tensor([2., 3.], requires_grad=True)
**>>> x
tensor([2., 3.], requires_grad=True)**
>>> s.x = pt.tensor([2., 3.], requires_grad=True)
[LOG]: get_attribute: key not found
[LOG]: get_attribute: key not found
[LOG]: get_attribute: key not found
[LOG]: get_attribute: key not found
[LOG]: HSTORE lock /home/moshikh/mcas/src/components/store/hstore/src/session.tcc:430 0x55e293d8d8a0 allocating object 8 bytes
[LOG]: HSTORE put /home/moshikh/mcas/src/components/store/hstore/src/hstore.cpp:345 0x55e293d97bb0 (key=x) (value=��)
[LOG]: HSTORE put /home/moshikh/mcas/src/components/store/hstore/src/hstore.cpp:345 0x55e293d97bb0 (key=x) (value=��)
[LOG]: put: already locked
made torch_tensor instance from copy 'x' on shelf
**>>> s.x
tensor([2., 3.], grad_fn=<AliasBackward>)**

>>> res = F.log_softmax(x, -1)
**>>> res
tensor([-1.3133, -0.3133], grad_fn=<LogSoftmaxBackward>)**
>>> s.res = F.log_softmax(x, -1)
[LOG]: get_attribute: key not found
[LOG]: get_attribute: key not found
[LOG]: get_attribute: key not found
[LOG]: get_attribute: key not found
[LOG]: HSTORE lock /home/moshikh/mcas/src/components/store/hstore/src/session.tcc:430 0x55e293d8d8a0 allocating object 8 bytes
[LOG]: HSTORE put /home/moshikh/mcas/src/components/store/hstore/src/hstore.cpp:345 0x55e293d97bb0 (key=res) (value=��)
[LOG]: HSTORE put /home/moshikh/mcas/src/components/store/hstore/src/hstore.cpp:345 0x55e293d97bb0 (key=res) (value=��)
[LOG]: put: already locked
made torch_tensor instance from copy 'res' on shelf
**>>> s.res
tensor([-1.3133, -0.3133], grad_fn=<AliasBackward>)**
