### ISSUE TITLE
Arithmetic exception on hstore resize value

### ISSUE THREAD

**Issue by dwaddington** [IBM/mcas#29]
Current test requires branch rust-wrapper and rustc nightly build.  Then after copying and modifying the .conf files for test system:

DAX_RESET=1 gdb --args ./dist/bin/mcas --config ./dist/conf/example-hstore-rust-ado.conf --forced-exit --debug 3
./dist/bin/ado-test  --gtest_filter=*Repeat* --server 10.0.0.101 --port 11911

```
#0  0x00007ffff4837c43 in session<open_pool<non_owner<region<impl::persist_data<allocator_rc<std::pair<persist_fixed_string<char, 24ul, deallocator_rc<char, persister_nupm> > const, std::tuple<persist_fixed_string<char, 24ul, deallocator_rc<char, persister_nupm> >, common::Timestamp<common::Timepoint> > >, persister_nupm>, std::pair<persist_fixed_string<char, 24ul, deallocator_rc<char, persister_nupm> > const, std::tuple<persist_fixed_string<char, 24ul, deallocator_rc<char, persister_nupm> >, common::Timestamp<common::Timepoint> > > >, heap_rc> > >, allocator_rc<char, persister_nupm>, hop_hash<persist_fixed_string<char, 24ul, deallocator_rc<char, persister_nupm> >, std::tuple<persist_fixed_string<char, 24ul, deallocator_rc<char, persister_nupm> >, common::Timestamp<common::Timepoint> >, pstr_hash<persist_fixed_string<char, 24ul, deallocator_rc<char, persister_nupm> > >, pstr_equal<persist_fixed_string<char, 24ul, deallocator_rc<char, persister_nupm> > >, allocator_rc<std::pair<persist_fixed_string<char, 24ul, deallocator_rc<char, persister_nupm> > const, std::tuple<persist_fixed_string<char, 24ul, deallocator_rc<char, persister_nupm> >, common::Timestamp<common::Timepoint> > >, persister_nupm>, dummy::shared_mutex>, component::IKVStore::lock_type_t>::resize_mapped (this=0x7fffec023260, 
    key="RUN!TEST-RepeatInvokeAdo", new_mapped_len=128, alignment=0)
    at /home/danielwaddington/mcas/src/components/store/hstore/src/session.h:529
#1  0x00007ffff4832aef in hstore::resize_value (this=0x7fffec014ae0, pool=618508845056, 
    key="RUN!TEST-RepeatInvokeAdo", new_value_len=128, alignment=0)
    at /home/danielwaddington/mcas/src/components/store/hstore/src/hstore.cpp:579
#2  0x0000000000486d71 in mcas::Shard::process_messages_from_ado (this=0x5a2b80)
    at /home/danielwaddington/mcas/src/server/mcas/src/shard_ado.cpp:769
#3  0x0000000000455d45 in mcas::Shard::main_loop (this=0x5a2b80, pr_=...)
    at /home/danielwaddington/mcas/src/server/mcas/src/shard.cpp:557
#4  0x000000000045493f in mcas::Shard::thread_entry (this=0x5a2b80, backend="hstore", 
    index="", dax_config="[{\"path\":\"/dev/dax0.0\",\"addr\":618475290624}]", debug_level=3, 
    ado_cores="2", ado_core_num=-1, profile_main_loop_=0x0, triggered_profile_=false)
    at /home/danielwaddington/mcas/src/server/mcas/src/shard.cpp:223
```

**Comment by dwaddington** [comment]
Note, the same test passes with mapstore.
